-- Tests for ado.sdk.http.errors module

describe('errors', function()
  local errors

  before_each(function()
    package.loaded['ado.sdk.http.errors'] = nil
    errors = require('ado.sdk.http.errors')
  end)

  describe('transport', function()
    it('identifies DNS resolution failures', function()
      local err = errors.transport(6, 'Could not resolve host: bad.example.com', '')
      assert.equals('transport', err.type)
      assert.is_nil(err.status_code)
      assert.truthy(err.message:match('network') or err.message:match('reach'))
    end)

    it('identifies connection refused', function()
      local err = errors.transport(7, 'Connection refused', '')
      assert.equals('transport', err.type)
      assert.truthy(err.message:match('refused') or err.message:match('Verify'))
    end)

    it('identifies operation timeout', function()
      local err = errors.transport(28, 'Operation timed out', '')
      assert.truthy(err.message:match('timed out'))
    end)

    it('identifies connection timeout', function()
      local err = errors.transport(28, 'Connection timed out', '')
      assert.truthy(err.message:match('timed out'))
    end)

    it('identifies SSL errors', function()
      local err = errors.transport(60, 'SSL certificate problem', '')
      assert.truthy(err.message:match('SSL'))
    end)

    it('extracts API message from stdout', function()
      local body = vim.json.encode({ message = 'Bad request details' })
      local err = errors.transport(22, '', body)
      assert.truthy(err.message:match('Bad request details'))
    end)

    it('falls back to stderr content', function()
      local err = errors.transport(99, 'some curl error', '')
      assert.truthy(err.message:match('some curl error'))
    end)

    it('falls back to exit code', function()
      local err = errors.transport(99, '', '')
      assert.truthy(err.message:match('99'))
    end)

    it('stores raw stderr', function()
      local err = errors.transport(6, 'some error', '')
      assert.equals('some error', err.raw)
    end)
  end)

  describe('http', function()
    it('extracts message from API error body', function()
      local body = vim.json.encode({ message = 'Not authorized' })
      local err = errors.http(401, body)
      assert.equals(401, err.status_code)
      assert.equals('http', err.type)
      assert.equals('Not authorized', err.message)
    end)

    it('has specific 401 message when no body message', function()
      local err = errors.http(401, '')
      assert.truthy(err.message:match('[Aa]uthenticat'))
    end)

    it('has specific 403 message', function()
      local err = errors.http(403, '')
      assert.truthy(err.message:match('[Aa]ccess'))
    end)

    it('has specific 404 message', function()
      local err = errors.http(404, '')
      assert.truthy(err.message:match('[Nn]ot found'))
    end)

    it('has generic message for other codes', function()
      local err = errors.http(500, '')
      assert.truthy(err.message:match('500'))
    end)

    it('stores raw body', function()
      local err = errors.http(500, '{"error":"details"}')
      assert.equals('{"error":"details"}', err.raw)
    end)
  end)

  describe('parse', function()
    it('includes parse error detail', function()
      local err = errors.parse('not json', 'Expected value at position 1')
      assert.equals('parse', err.type)
      assert.is_nil(err.status_code)
      assert.truthy(err.message:match('parse') or err.message:match('Parse'))
      assert.equals('not json', err.raw)
    end)
  end)

  describe('validation', function()
    it('creates error with message', function()
      local err = errors.validation('project is required')
      assert.equals('validation', err.type)
      assert.equals('project is required', err.message)
      assert.is_nil(err.status_code)
      assert.is_nil(err.raw)
    end)
  end)

  describe('response_too_large', function()
    it('creates error with size info', function()
      local err = errors.response_too_large(20 * 1024 * 1024, 10 * 1024 * 1024)
      assert.equals('transport', err.type)
      assert.truthy(err.message:match('large') or err.message:match('Large'))
    end)
  end)
end)
